version: '3'

services:  
  neo4j:
    image: neo4j:3.4
    ports:
      - "7474"
      - "7687"
    environment:
      - NEO4j_dbms_security_auth__enabled=false
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes

  jupyter:
    build: .
    ports:
      - "8888"
    environment:
      - PASSWORD=password


  web:
    image: nginx
    depends_on:
      - neo4j
      - jupyter
    ports:
     - "8080:80"
     - "7687:7687"
    environment:
     - NGINX_PORT=80
    volumes:
     - "./nginx.conf:/etc/nginx/nginx.conf"

